# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e76c28712ca52490246c4d6d8ab2ce555f914840e16d5db7d56a41a65962033c28265a0419b17a13d61da6c47f9d00bb7c34655d07a30cc56eff6a449485bc

test:
  secret_key_base: c1c1d21a0ba483ce373995aa91bd4fff24fb27d5dff5fac585b8b336a4a8752a15978102a404c361c5e845c08887e60ff1b6b7a2f5d80c2d5fbc37328924c5a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
